### ISSUE TITLE
Job aborted error 2

### ISSUE THREAD

**Issue by mloutsaris** [marouni/spark-yarn-miner#1]
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 1.0 failed 4 times, most recent failure: Lost task 2.3 in stage 1.0 (TID 10, nodes.pc6): java.io.IOException: Cannot run program "/tmp/spark-3e90bb9c-2f06-4b29-b0b6-6337c1af169d/userFiles-536ff551-45ba-45de-9bbd-2d08c96a47b8/runner.sh": error=2, No such file or directory

Can you help me to solve this problem?

**Comment by marouni** [comment]
@mloutsaris Can you please show me the whole command that you used to start the spark-yarn-miner ?

**Comment by mloutsaris** [comment]
@marouni Of course, it's the same as you described `spark-submit --master yarn --class fr.marouni.spark.coins.SparkYarnMiner spark-yarn-miner_2.11-0.1.0-SNAPSHOT.jar --url XXX --username YYY --worker-id WWW --password UUUU` but i tried also `spark-submit --master yarn --class fr.marouni.spark.coins.SparkYarnMiner spark-yarn-miner_2.11-0.1.0-SNAPSHOT.jar --conf spark.executor.instances=6 --url XXX --username YYY --worker-id WWW --password UUUU`

Thank you very much for your help

**Comment by marouni** [comment]
@mloutsaris I've just compiled and ran the miner with the latest apache spark 2.4 (on local) using : 
`./bin/spark-submit --class fr.marouni.spark.coins.SparkYarnMiner spark-yarn-miner_2.11-0.1.0-SNAPSHOT.jar --url XXX --username YYY --worker-id WWW --password UUUU` 

Did notice any issues (apart from the fact that XXX, YYY, WWW & UUU should be replaced with a valid account).

What's your Hadoop/Yarn version ?

**Comment by mloutsaris** [comment]
Sorry for the late answer but one power loss kill my master node, so i had to setup it again. Well, my hadoop version is 2.8.1 and spark version 2.4 . The 

`2018-11-22 01:54:32 WARN  TaskSetManager:66 - Lost task 0.0 in stage 1.0 (TID 0, islab.pc5, executor 1): java.io.IOException: Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.rdd.PipedRDD.compute(PipedRDD.scala:111)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 11 more

2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 0.1 in stage 1.0 (TID 4, islab.pc5, executor 1, partition 0, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 2.0 in stage 1.0 (TID 2) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 1]
2018-11-22 01:54:32 INFO  BlockManagerMasterEndpoint:54 - Registering block manager islab.pc2:34305 with 93.1 MB RAM, BlockManagerId(2, islab.pc2, 34305, None)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 3.0 in stage 1.0 (TID 3) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 2]
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 3.1 in stage 1.0 (TID 5, islab.pc5, executor 1, partition 3, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 0.1 in stage 1.0 (TID 4) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 3]
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 0.2 in stage 1.0 (TID 6, islab.pc5, executor 1, partition 0, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 3.1 in stage 1.0 (TID 5) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 4]
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 3.2 in stage 1.0 (TID 7, islab.pc5, executor 1, partition 3, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 0.2 in stage 1.0 (TID 6) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 5]
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 0.3 in stage 1.0 (TID 8, islab.pc5, executor 1, partition 0, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 3.2 in stage 1.0 (TID 7) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 6]
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Starting task 3.3 in stage 1.0 (TID 9, islab.pc5, executor 1, partition 3, PROCESS_LOCAL, 7949 bytes)
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 0.3 in stage 1.0 (TID 8) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 7]
2018-11-22 01:54:32 ERROR TaskSetManager:70 - Task 0 in stage 1.0 failed 4 times; aborting job
2018-11-22 01:54:32 INFO  YarnScheduler:54 - Cancelling stage 1
2018-11-22 01:54:32 INFO  YarnScheduler:54 - Killing all running tasks in stage 1: Stage cancelled
2018-11-22 01:54:32 INFO  YarnScheduler:54 - Stage 1 was cancelled
2018-11-22 01:54:32 INFO  TaskSetManager:54 - Lost task 3.3 in stage 1.0 (TID 9) on islab.pc5, executor 1: java.io.IOException (Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory) [duplicate 8]
2018-11-22 01:54:32 INFO  DAGScheduler:54 - ResultStage 1 (count at SparkYarnMiner.scala:44) failed in 24.647 s due to Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 8, islab.pc5, executor 1): java.io.IOException: Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.rdd.PipedRDD.compute(PipedRDD.scala:111)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 11 more

Driver stacktrace:
2018-11-22 01:54:32 INFO  DAGScheduler:54 - Job 0 failed: count at SparkYarnMiner.scala:44, took 25.135558 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 8, islab.pc5, executor 1): java.io.IOException: Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.rdd.PipedRDD.compute(PipedRDD.scala:111)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 11 more

Driver stacktrace:
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
        at scala.Option.foreach(Option.scala:257)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
        at org.apache.spark.rdd.RDD.count(RDD.scala:1168)
        at fr.marouni.spark.coins.SparkYarnMiner$.main(SparkYarnMiner.scala:44)
        at fr.marouni.spark.coins.SparkYarnMiner.main(SparkYarnMiner.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.IOException: Cannot run program "/tmp/spark-73d05a03-cc71-48e5-b721-8c5a1ed29dff/userFiles-4b80c4cc-6da9-4dcd-af25-cb5c0e160aa5/runner.sh": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.rdd.PipedRDD.compute(PipedRDD.scala:111)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 11 more
`

This is the logs .

**Comment by mloutsaris** [comment]
No all were going well until these appeared.

**Comment by mloutsaris** [comment]
@marouni i think that the script is only on master-node and does not shared with the other nodes. So, when i spark-submit through the node-master, the other nodes cant find the script to run it.

**Comment by mloutsaris** [comment]
@marouni Hello, do you have any idea about the problem?

**Comment by marouni** [comment]
@mloutsaris Currently I don't have a running Hadoop cluster to test this, but I did all sorts of tests on real Hadoop clusters when I first wrote this.

I'll retest again and get back to you ASAP.

Thanks,

**Comment by mloutsaris** [comment]
@marouni Thank you very much for your help. I can give you any information about my cluster. i followed these instructions for hadoop and spark
https://www.linode.com/docs/databases/hadoop/how-to-install-and-set-up-hadoop-cluster/
https://www.linode.com/docs/databases/hadoop/install-configure-run-spark-on-top-of-hadoop-yarn-cluster/
All examples running fine. My OS is Centos 7 i386.
